import { test, expect } from '@playwright/test'
import { bodyHash, bodyPlainText, summaryVerdict } from '../lib/summary'

// PROPOSALS 5.6. The suppression rules are the whole feature until generation exists, and
// they are pure functions, so they get exact tests rather than a look at a rendered panel.
//
// Both rules fail CLOSED. On a site whose subject is epistemic honesty, a summary that is
// merely probably still accurate is worth less than no summary, so every uncertain case
// hides it. These tests exist to stop a later change making one of them fail open.

const para = (text: string) => ({ _type: 'block', children: [{ text }] })
const BODY = [para('The first paragraph.'), para('The second paragraph.')]
const HASH = bodyHash(bodyPlainText(BODY))

const base = {
  summary: 'A short summary of the post.',
  summarySource: 'authored',
  summaryAt: '2026-09-01T00:00:00Z',
  summaryOfHash: HASH,
}

test.describe('5.6 summary suppression', () => {
  test('shows when the fingerprint matches and nothing has corrected it', () => {
    const v = summaryVerdict(base, BODY)
    expect(v.show).toBe(true)
    if (v.show) expect(v.text).toBe('A short summary of the post.')
  })

  test('an empty summary renders nothing', () => {
    expect(summaryVerdict({ ...base, summary: '   ' }, BODY)).toEqual({ show: false, reason: 'absent' })
  })

  test('EDITING THE PROSE suppresses it — stale, never shown stale', () => {
    const edited = [para('The first paragraph, rewritten.'), para('The second paragraph.')]
    expect(summaryVerdict(base, edited)).toEqual({ show: false, reason: 'stale' })
  })

  test('a missing fingerprint counts as stale, not as a pass', () => {
    expect(summaryVerdict({ ...base, summaryOfHash: null }, BODY)).toEqual({ show: false, reason: 'stale' })
  })

  test('re-cropping an image does NOT invalidate a summary of the prose', () => {
    // Non-text blocks contribute nothing to the fingerprint on purpose: a summary describes
    // the writing, so only the writing should be able to invalidate it.
    const withImage = [para('The first paragraph.'), { _type: 'image', children: null }, para('The second paragraph.')]
    expect(summaryVerdict(base, withImage).show).toBe(true)
  })

  test('A CORRECTION NEWER THAN THE SUMMARY suppresses it', () => {
    // The failure this prevents: a post carries a correction saying it was wrong, and a
    // summary two panels away confidently restates the corrected claim.
    expect(summaryVerdict(base, BODY, ['2026-09-02'])).toEqual({ show: false, reason: 'corrected' })
  })

  test('a correction OLDER than the summary does not', () => {
    expect(summaryVerdict(base, BODY, ['2026-08-01']).show).toBe(true)
  })

  test('a correction with no summary date suppresses, because they cannot be ordered', () => {
    expect(summaryVerdict({ ...base, summaryAt: null }, BODY, ['2026-08-01'])).toEqual({ show: false, reason: 'corrected' })
  })

  test('the newest correction decides, not the first in the array', () => {
    expect(summaryVerdict(base, BODY, ['2026-08-01', '2026-09-30', '2026-08-15']).show).toBe(false)
  })
})

test.describe('5.6 summary labelling', () => {
  test('an AUTHORED summary carries no machine label', () => {
    const v = summaryVerdict(base, BODY)
    expect(v.show && v.label).toBe(null)
  })

  test('a GENERATED summary names the model and the date, visibly', () => {
    const v = summaryVerdict(
      { ...base, summarySource: 'generated', summaryModel: 'claude-haiku-4-5' },
      BODY, [], (iso) => iso.slice(0, 10),
    )
    expect(v.show).toBe(true)
    if (v.show) {
      expect(v.label).toContain('claude-haiku-4-5')
      expect(v.label).toContain('2026-09-01')
      expect(v.label?.startsWith('Summary · generated by')).toBe(true)
    }
  })

  test('a generated summary with no model still says a model wrote it', () => {
    const v = summaryVerdict({ ...base, summarySource: 'generated', summaryModel: null }, BODY)
    expect(v.show && v.label).toContain('a language model')
  })

  test('an unknown source is treated as generated, not as authored', () => {
    // Fail closed on labelling too: the dishonest direction is presenting a machine's
    // paraphrase as the author's, so anything that is not explicitly 'authored' is labelled.
    const v = summaryVerdict({ ...base, summarySource: null }, BODY)
    expect(v.show && v.label).not.toBe(null)
  })
})
