// lib/summary.ts — PROPOSALS 5.6, the half that ships before any generation exists.
//
// Stefan's decision: build the field, the label, the suppression rules and
// correction-invalidates-summary NOW, with summaries written by hand. No generation yet.
//
// That order is deliberate. It ships the reader-facing half with zero API cost and zero
// failure modes, and it means the generation step, when it lands, is a webhook that fills in
// a field whose every consumer already works.
//
// No React and no server-only import: the schema (which runs in the Studio) and the render
// path both read this file.

/** Minimal Portable Text shape. Anything without children contributes no text. */
type Block = { _type?: string; children?: Array<{ text?: string | null } | null> | null } | null

/**
 * The plain text a summary describes.
 *
 * Blocks are joined with "\n" and non-text blocks contribute nothing, which is the point:
 * re-cropping an image or reordering two code blocks must NOT invalidate a summary of the
 * prose, while editing a sentence must.
 */
export function bodyPlainText(body: Block[] | null | undefined): string {
  if (!Array.isArray(body)) return ''
  return body
    .map((b) => (b?.children ?? []).map((c) => c?.text ?? '').join(''))
    .filter((s) => s.trim().length > 0)
    .join('\n')
}

/**
 * FNV-1a, 32-bit, base36.
 *
 * Not a cryptographic hash and it does not need to be. It answers one question — "is this
 * the same prose the summary was written about?" — where the adversary is an author editing
 * their own post, not an attacker. Short enough to eyeball in the Studio.
 */
export function bodyHash(text: string): string {
  let h = 0x811c9dc5
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h.toString(36)
}

export type SummarySource = 'generated' | 'authored'

export type SummaryInput = {
  summary?: string | null
  summarySource?: string | null
  summaryModel?: string | null
  summaryAt?: string | null
  summaryOfHash?: string | null
}

export type SummaryVerdict =
  | { show: false; reason: 'absent' | 'stale' | 'corrected' }
  | { show: true; text: string; label: string | null }

/**
 * Whether to show the summary, and what to label it.
 *
 * TWO suppression rules, and both fail CLOSED. A summary that is merely probably still
 * accurate is worth less than no summary at all on a site whose subject is epistemic
 * honesty, so every uncertain case hides it.
 *
 * 1. STALE. `summaryOfHash` is the hash of the prose the summary was written about. When it
 *    does not match the current body, the summary is suppressed rather than shown stale.
 *    This is what makes staleness DETECTED rather than assumed, and it is the reason the
 *    field is stored on the document instead of cached: a cache can be evicted and silently
 *    regenerated, which would throw away a hand-written override.
 *
 * 2. CORRECTED. A correction dated after the summary suppresses it outright. The failure
 *    this prevents is specific and bad: a post carries a correction saying it was wrong, and
 *    an AI summary two panels away confidently restates the thing that was corrected. A
 *    correction must invalidate the summary; nothing else on the page is allowed to disagree
 *    with a correction.
 *
 * The LABEL is only ever attached to a generated summary. When Stefan writes it himself the
 * label goes away entirely, because labelling authored text as machine-written would be its
 * own kind of dishonesty.
 */
export function summaryVerdict(
  post: SummaryInput,
  body: Block[] | null | undefined,
  correctionDates: Array<string | null | undefined> = [],
  formatDate: (iso: string) => string = (iso) => iso.slice(0, 10),
): SummaryVerdict {
  const text = (post.summary ?? '').trim()
  if (!text) return { show: false, reason: 'absent' }

  // Rule 1. An empty stored hash means "never recorded", which is treated as stale rather
  // than as a pass -- a summary whose subject we cannot identify is exactly the uncertain
  // case these rules exist to hide.
  const current = bodyHash(bodyPlainText(body))
  if (!post.summaryOfHash || post.summaryOfHash !== current) return { show: false, reason: 'stale' }

  // Rule 2. Any correction newer than the summary invalidates it. With no summaryAt there is
  // no way to order them, so any correction at all suppresses.
  const corrections = correctionDates.filter((d): d is string => Boolean(d))
  if (corrections.length > 0) {
    if (!post.summaryAt) return { show: false, reason: 'corrected' }
    const newest = corrections.reduce((a, b) => (a > b ? a : b))
    if (newest > post.summaryAt) return { show: false, reason: 'corrected' }
  }

  const generated = post.summarySource !== 'authored'
  const label = generated
    ? `Summary · generated by ${post.summaryModel || 'a language model'}${post.summaryAt ? `, ${formatDate(post.summaryAt)}` : ''}`
    : null

  return { show: true, text, label }
}
